### ISSUE TITLE
Aligned image in output anndata

### ISSUE THREAD

**Issue by ConstensouxAlexis** [Sanofi-Public/enact-pipeline#15]
Hello,
Thank you again for this pipeline, it will be very useful for our lab working a lot on VisiumHD data ! However, the output anndata does not contain the aligned image; thus we cannot plot clusters/genes expression/etc ... Do you plan to add the aligned image in the anndata output (or in a spatialdata object, that would allow to vizualise cell shape) ? This would be really helpful for downtream analysis ! 

I also have an issue with .tmap file, that we cannot open in TissUUmap; do you have any idea of what could be the issue ?
![image](https://github.com/user-attachments/assets/b0e3856c-b808-440b-ab9d-80eb0243a434)

Thank you a lot

**Comment by Mena-SA-Kamel** [comment]
Hello there! This error has been resolved in the most recent release.  

We now save a cropped version of the .tif image file under the tmap/ folder:
![image](https://github.com/user-attachments/assets/d1b6299e-b2bd-40df-933a-94452561a410)
Can you ensure you are using this wsi.tif file NOT the original whole slide image specified under paths/wsi_path?

This is the relevant code snippet that saves the cropped image in which the cells in the Anndata object should be aligned to: [code snippet](https://github.com/Sanofi-Public/enact-pipeline/blob/eecf0a9f95d6c435cbe0bdf98424feb8a93ce278/src/enact/package_results.py#L159C1-L163C45)

The reason why we save a cropped version of the whole slide image is to make the image file sizes manageable to render on personal PCs.

Regarding the tmap file not loading, please ensure all the relevant files are in the same directory with the .tmap file you are trying to view on TissUUmaps? (.tmap file, .h5 anndata file, and .tif image file).

**Comment by alexanderchang1** [comment]
How would one load this cropped wsi file into the anndata object so it's compatible with downstream functions like scanpy spatial plot?
