### ISSUE TITLE
Using a scRNA as reference to train custom CellTypist models (or load custom pre-trained CellTypist models)

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [Sanofi-Public/enact-pipeline#7]
Hey! really excited about this tool and thrilled to see more progress being made on Visium HD! Currently, it seems the primary methods in enact for cell annotation rely on cell markers or pre-trained models (especially with CellTypist). I’m curious if there are any plans to use annotated scRNA datasets as references for CellTypist, enabling users to train custom models from scratch based on their own scRNA data and then apply these models to infer spatial cell types. I think the fastest way to enable this would be to at least allow users to load their own custom CellTypist models, as it currently appears to load only from pre-existing models in CellTypist (though please correct me if I've missed something on this!).

An approach similar to what's described in this article (https://www.sciencedirect.com/science/article/abs/pii/S0010482523000999), where a cell marker finder is integrated with annotated scRNA datasets, could also be helpful for using those markers to identify spatial cells

Thanks again for all the great work!

**Comment by Mena-SA-Kamel** [comment]
Hi Rafael, thank you so much for your very valuable insight. We can certainly add ability to load pre-trained CellTypist models in future releases. This sounds like a simple and reasonable ask.
Regarding the use of scMAGS, this could be useful to mention in the Readme.

**Comment by TatianaSezin** [comment]
Hi guys, 

just finished generating our first Visium HD data and was very excited to read about ENACT.
I tried to run the output from our HD Visium results in human skin using ENACT. These were the parameters we used: 

 segmentation: True
 bin_to_geodataframes: True
 bin_to_cell_assignment: True
 cell_type_annotation: True
 seg_method: stardist
 patch_size: 4000
 bin_representation: polygon
 bin_to_cell_method: weighted_by_cluster
 cell_annotation_method: celltypist
 cell_typist_model: Adult_Human_Skin.pkl
 use_hvg: True
 n_hvg: 1000
 n_clusters: 4

We obtained 6 patches. Is there a way to control the number of patches that are generated? Is there a way to visualize the segmentation results? May you please suggest how one should use the ouput from ENACT to continue visualizing the annotated clusters in SquidPy? 

Thank you so much in advance for any input and your great support so far!
